### ISSUE TITLE
error

### ISSUE THREAD

**Issue by onix010** [tegal1337/YOMEN#49]
C:\Users\m\Downloads\YT-Comment-Bot-master\YOMEN-main\YOMEN-main\main.js:66
  await page.setUserAgent(randomUserAgent.UA());
                                          ^

TypeError: Cannot read properties of undefined (reading 'UA')
    at startApp (C:\Users\m\Downloads\YT-Comment-Bot-master\YOMEN-main\YOMEN-main\main.js:66:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by onix010** [comment]
C:\Users\m\Downloads\YT-Comment-Bot-master\YOMEN-main\YOMEN-main\main.js:66
  await page.setUserAgent(randomUserAgent.UA());
                                                                          ^

TypeError: Cannot read properties of undefined (reading 'UA')
    at startApp (C:\Users\m\Downloads\YT-Comment-Bot-master\YOMEN-main\YOMEN-main\main.js:66:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by onix010** [comment]
the error is at .UA TypeError: Cannot read properties of undefined (reading 'UA')

**Comment by fdciabdul** [comment]
Fixed , please update to latest

**Comment by onix010** [comment]
let me try thanks
